import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/pdf_report_data.dart';
import '../models/transaction.dart';
import '../models/account.dart';
import '../utils/currency_utils.dart';

class PdfReportService {
  static final PdfReportService _instance = PdfReportService._internal();
  factory PdfReportService() => _instance;
  PdfReportService._internal();

  late NumberFormat _currencyFormatter;

  Future<bool> generateAndShareReport(PdfReportData data) async {
    try {
      _currencyFormatter = CurrencyUtils.getFormatter(data.displayCurrency);
      final pdfBytes = await _buildPdf(data);
      final timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());

      await Printing.sharePdf(
        bytes: pdfBytes,
        filename: 'financial_report_$timestamp.pdf',
      );
      return true;
    } catch (_) {
      return false;
    }
  }

  Future<Uint8List> _buildPdf(PdfReportData data) async {
    final pdf = pw.Document(
      title: 'Financial Report - ${data.periodLabel}',
      author: 'Personal Manager',
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(data),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildOverviewSection(data),
          pw.SizedBox(height: 20),
          _buildCategorySection(data),
          pw.SizedBox(height: 20),
          _buildTransactionsSection(data),
          pw.SizedBox(height: 20),
          _buildAccountsSection(data),
          pw.SizedBox(height: 20),
          _buildLoansSection(data),
          pw.SizedBox(height: 20),
          _buildLiabilitiesSection(data),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(PdfReportData data) {
    return pw.Container(
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.blue800, width: 2),
        ),
      ),
      padding: const pw.EdgeInsets.only(bottom: 8),
      margin: const pw.EdgeInsets.only(bottom: 16),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Personal Manager',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                'Financial Report',
                style: const pw.TextStyle(
                  fontSize: 14,
                  color: PdfColors.grey700,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Period: ${data.periodLabel} (${data.periodType})',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                'Generated on',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey500,
                ),
              ),
              pw.Text(
                DateFormat('dd MMM yyyy, HH:mm').format(data.generatedAt),
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.center,
      margin: const pw.EdgeInsets.only(top: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by Personal Manager',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildOverviewSection(PdfReportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Overview Summary'),
        pw.SizedBox(height: 8),
        pw.Row(
          children: [
            pw.Expanded(
              child: _metricBox(
                  'Total Income', data.totalIncome, PdfColors.green800),
            ),
            pw.SizedBox(width: 12),
            pw.Expanded(
              child: _metricBox(
                  'Total Expense', data.totalExpense, PdfColors.red800),
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Row(
          children: [
            pw.Expanded(
              child: _metricBox(
                'Net Balance',
                data.netBalance,
                data.netBalance >= 0 ? PdfColors.green800 : PdfColors.red800,
              ),
            ),
            pw.SizedBox(width: 12),
            pw.Expanded(
              child: _metricBox(
                  'Total Assets', data.totalAssets, PdfColors.blue800),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _metricBox(String label, double value, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        border: pw.Border(left: pw.BorderSide(color: color, width: 3)),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            _currencyFormatter.format(value),
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 4),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 1),
        ),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue900,
        ),
      ),
    );
  }

  pw.Widget _buildCategorySection(PdfReportData data) {
    if (data.expensesByCategory.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Expense by Category'),
          pw.SizedBox(height: 8),
          pw.Text(
            'No expense data for this period.',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      );
    }

    final totalExpense =
        data.expensesByCategory.values.fold(0.0, (sum, v) => sum + v);
    final sorted = data.expensesByCategory.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final top = sorted.take(10).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Expense by Category'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle:
              pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          cellStyle: const pw.TextStyle(fontSize: 9),
          headerDecoration:
              const pw.BoxDecoration(color: PdfColors.blue50),
          cellHeight: 24,
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(1),
          },
          headers: ['Category', 'Amount', '%'],
          data: top.map((e) {
            final pct = totalExpense > 0
                ? (e.value / totalExpense * 100).toStringAsFixed(1)
                : '0.0';
            return [e.key, _currencyFormatter.format(e.value), '$pct%'];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildTransactionsSection(PdfReportData data) {
    final sorted = List.of(data.transactions)
      ..sort((a, b) => b.date.compareTo(a.date));

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Transactions (${sorted.length})'),
        pw.SizedBox(height: 8),
        if (sorted.isEmpty)
          pw.Text(
            'No transactions in this period.',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          )
        else
          pw.TableHelper.fromTextArray(
            headerStyle:
                pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
            cellStyle: const pw.TextStyle(fontSize: 8),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColors.blue50),
            cellHeight: 22,
            columnWidths: {
              0: const pw.FixedColumnWidth(60),
              1: const pw.FixedColumnWidth(70),
              2: const pw.FlexColumnWidth(),
              3: const pw.FixedColumnWidth(65),
              4: const pw.FixedColumnWidth(45),
              5: const pw.FixedColumnWidth(80),
            },
            headers: [
              'Date',
              'Category',
              'Description',
              'Account',
              'Type',
              'Amount',
            ],
            data: sorted.map((t) {
              final accountName = _getAccountName(t.accountId, data.accounts);
              final prefix =
                  t.type == TransactionType.expense ? '-' : '+';
              return [
                DateFormat('dd/MM/yy').format(t.date),
                t.category ?? '-',
                t.description ?? '-',
                accountName,
                t.type.name[0].toUpperCase() + t.type.name.substring(1),
                '$prefix${_currencyFormatter.format(t.amount)}',
              ];
            }).toList(),
          ),
      ],
    );
  }

  pw.Widget _buildAccountsSection(PdfReportData data) {
    if (data.accounts.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Account Balances'),
          pw.SizedBox(height: 8),
          pw.Text(
            'No accounts found.',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Account Balances'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle:
              pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          cellStyle: const pw.TextStyle(fontSize: 9),
          headerDecoration:
              const pw.BoxDecoration(color: PdfColors.blue50),
          cellHeight: 24,
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
          },
          headers: ['Account', 'Type', 'Balance'],
          data: data.accounts.map((a) {
            return [
              a.name,
              _formatAccountType(a.type),
              _currencyFormatter.format(a.balance),
            ];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildLoansSection(PdfReportData data) {
    final activeLoans = data.loans.where((l) => !l.isReturned).toList();
    if (activeLoans.isEmpty && data.loans.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Loans Given'),
          pw.SizedBox(height: 8),
          pw.Text(
            'No loans recorded.',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Loans Given (${data.loans.length})'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle:
              pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          cellStyle: const pw.TextStyle(fontSize: 9),
          headerDecoration:
              const pw.BoxDecoration(color: PdfColors.blue50),
          cellHeight: 24,
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(1),
          },
          headers: ['Person', 'Amount', 'Loan Date', 'Status'],
          data: data.loans.map((l) {
            return [
              l.personName,
              _currencyFormatter.format(l.amount),
              DateFormat('dd/MM/yy').format(l.loanDate),
              l.isReturned ? 'Returned' : 'Active',
            ];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildLiabilitiesSection(PdfReportData data) {
    if (data.liabilities.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle('Liabilities (Money Owed)'),
          pw.SizedBox(height: 8),
          pw.Text(
            'No liabilities recorded.',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Liabilities (${data.liabilities.length})'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle:
              pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          cellStyle: const pw.TextStyle(fontSize: 9),
          headerDecoration:
              const pw.BoxDecoration(color: PdfColors.blue50),
          cellHeight: 24,
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(2),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(1),
          },
          headers: ['Person', 'Amount', 'Due Date', 'Status'],
          data: data.liabilities.map((l) {
            String status;
            if (l.isPaid) {
              status = 'Paid';
            } else if (l.isOverdue) {
              status = 'OVERDUE';
            } else {
              status = 'Pending';
            }
            return [
              l.personName,
              _currencyFormatter.format(l.amount),
              DateFormat('dd/MM/yy').format(l.dueDate),
              status,
            ];
          }).toList(),
        ),
      ],
    );
  }

  String _getAccountName(String accountId, List<Account> accounts) {
    final account = accounts.where((a) => a.id == accountId).firstOrNull;
    return account?.name ?? 'Unknown';
  }

  String _formatAccountType(AccountType type) {
    switch (type) {
      case AccountType.wallet:
        return 'Wallet';
      case AccountType.bank:
        return 'Bank';
      case AccountType.mobileBanking:
        return 'Mobile Banking';
      case AccountType.cash:
        return 'Cash';
      case AccountType.investment:
        return 'Investment';
      case AccountType.savings:
        return 'Savings';
      case AccountType.creditCard:
        return 'Credit Card';
    }
  }
}
